const lang = {
	"en": {
		"lobby": {
			"edit-button": "save",
			"header-link-faq": "Rules and FAQs",
			"header-link-education": "Educational game",
			"invite-text": "invites you",
			"invite-accept": "Accept",
			"invite-decline": "Decline",
			"ban-title": "You started a search and did not accept the game",
			"ban-text": "You can start your next game search via",
			"rank-title": "Regular / Tournament Rank",
			"choose-character": "Choose character",
			"prize": "Tournament prize",
			"lobby-title": "Players on board",
			"private-party": "Private party for 6 friends",
			"competitive-party": "Competitive party for 2 friends",
			"competitive": "Competitive",
			"private": "Private party",
			"start-search-default": "Start Search",
			"start-search-waiting": "Waiting...",
			"friends": "Friends",
			"friend-requests-default": "Friend Requests",
			"friend-requests-close": "Close"
		},
		"game": {
			"play-card": "You can play a card",
			"deck": "Card deck",
			"end-turn": "End turn",
			"how-to-play": "How to play",
			"history": "History",
			"leave-game": "Back to lobby",
			"you": "You",
			"get-cards-from-deck-2": "take 2 cards from deck",
			"get-cards-from-deck-3": "take 3 cards from deck",
			"play": "play",
			"plays": "plays",
			"and-you-choose": "&nbspand choose player",
			"and-choose": "&nbspand choose player",
			"as-target": "as target",
			"move": "Move",
			"choose-cards": "Choose cards to get",
			"check-cards": "Choose cards to check",
			"sheriff-win": "SHERIFF WINS",
			"maniac-win": "MANIAC WINDS",
			"bandit-win": "BANDITS WIN"
		}
	},
	"ru": {
		"lobby": {
			"edit-button": "сохранить",
			"header-link-faq": "Правила и FAQs",
			"header-link-education": "Обучающая игра",
			"invite-text": "пригласил вас",
			"invite-accept": "Принять",
			"invite-decline": "Отклонить",
			"ban-title": "Вы начали поиск и не приняли игру",
			"ban-text": "Начать следующий поиск игры сможете через",
			"rank-title": "Обычный / Турнирный Рейтинг",
			"choose-character": "Выбор персонажа",
			"prize": "Награды турнира",
			"lobby-title": "Игроки за этим столом",
			"private-party": "Приватное пати для 6 друзей",
			"competitive-party": "Соревновательное пати для 2 друзей",
			"competitive": "Соревновательный",
			"private": "Приватное пати",
			"start-search-default": "Начать поиск",
			"start-search-waiting": "Ожидание...",
			"friends": "Друзья",
			"friend-requests-default": "Заявка в друзья",
			"friend-requests-close": "Закрыть"
		},
		"game": {
			"play-card": "Вы можете сыграть карту",
			"deck": "Колода карт",
			"end-turn": "Завершить ход",
			"how-to-play": "Как играть",
			"history": "Журнал повтора",
			"leave-game": "Вернуться в главное меню",
			"shop": " выбирает карту для эффекта Магазин",
			"you": "Вы",
			"you-get-cards-from-deck-2": "берете 2 карты из колоды",
			"you-get-cards-from-deck-3": "берете 3 карты из колоды",
			"get-cards-from-deck-2": "берет 2 карты из колоды",
			"get-cards-from-deck-3": "берет 3 карты из колоды",
			"play": "играете",
			"plays": "играет",
			"and-you-choose": "&nbspи выбираете игрока",
			"and-choose": "&nbspи выбирает игрока",
			"as-target": "в качестве цели",
			"move": "Ход",
			"choose-cards": "Выбор карты для набора",
			"check-cards": "Выбор карты для проверки",
			"sheriff-win": "ПОБЕДА ШЕРИФА",
			"maniac-win": "ПОБЕДА МАНЬЯКА",
			"bandit-win": "ПОБЕДА БАНДИТОВ"
		}
	}
}